// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_BROADWELL_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_BROADWELL_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models broadwell = {
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.093, min=0.802, max=1.249 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/7.64e-10f,
        /*load_a_cost=*/1.96e-10f,
        /*load_b_cost=*/5.09e-11f,
        /*output_c=*/7.91e-11f,
    },
    // Ratio (predicted / actual): std=0.112, min=0.776, max=1.226 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/8.47e-10f,
        /*load_a_cost=*/2.02e-10f,
        /*load_b_cost=*/9.39e-11f,
        /*output_c=*/1.41e-10f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.101, min=0.768, max=1.210 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.23e-10f,
        /*load_b_cost=*/6.58e-11f,
        /*output_c=*/8.03e-11f,
    },
    // Ratio (predicted / actual): std=0.039, min=0.893, max=1.099 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/1.64e-09f,
        /*load_a_cost=*/6.38e-10f,
        /*load_b_cost=*/5.24e-11f,
        /*output_c=*/5.10e-11f,
    },
    // Ratio (predicted / actual): std=0.047, min=0.859, max=1.094 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/2.56e-09f,
        /*load_a_cost=*/1.22e-11f,
        /*load_b_cost=*/1.37e-10f,
        /*output_c=*/9.64e-10f,
    },
    // Ratio (predicted / actual): std=0.093, min=0.798, max=1.220 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/5.25e-09f,
        /*load_a_cost=*/1.10e-10f,
        /*load_b_cost=*/4.42e-11f,
        /*output_c=*/6.18e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.098, min=0.797, max=1.201 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/7.82e-10f,
        /*load_a_cost=*/2.04e-10f,
        /*load_b_cost=*/2.17e-11f,
        /*output_c=*/7.08e-11f,
    },
    // Ratio (predicted / actual): std=0.027, min=0.902, max=1.061 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.39e-10f,
        /*load_b_cost=*/2.92e-11f,
        /*output_c=*/1.78e-10f,
    },
    // Ratio (predicted / actual): std=0.029, min=0.882, max=1.045 (n=60)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.19e-10f,
        /*load_b_cost=*/4.28e-11f,
        /*output_c=*/9.08e-11f,
    },
    // Ratio (predicted / actual): std=0.163, min=0.719, max=1.333 (n=120)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.20e-10f,
        /*load_b_cost=*/2.50e-11f,
        /*output_c=*/2.73e-10f,
    },
    // Ratio (predicted / actual): std=0.085, min=0.830, max=1.134 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.35e-11f,
        /*load_b_cost=*/3.26e-11f,
        /*output_c=*/2.33e-10f,
    },
    // Ratio (predicted / actual): std=0.131, min=0.677, max=1.274 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/1.70e-09f,
        /*load_a_cost=*/1.39e-10f,
        /*load_b_cost=*/6.72e-11f,
        /*output_c=*/1.94e-10f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.087, min=0.749, max=1.196 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/3.97e-09f,
        /*load_a_cost=*/2.61e-10f,
        /*load_b_cost=*/6.34e-11f,
        /*output_c=*/3.08e-11f,
    },
    // Ratio (predicted / actual): std=0.089, min=0.809, max=1.205 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/3.27e-09f,
        /*load_a_cost=*/2.63e-10f,
        /*load_b_cost=*/1.26e-10f,
        /*output_c=*/8.44e-11f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.048, min=0.882, max=1.224 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/2.12e-09f,
        /*load_a_cost=*/1.19e-09f,
        /*load_b_cost=*/1.45e-11f,
        /*output_c=*/2.90e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.091, min=0.828, max=1.194 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/1.19e-09f,
        /*load_a_cost=*/1.11e-09f,
        /*load_b_cost=*/4.32e-11f,
        /*output_c=*/5.54e-11f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.108, min=0.745, max=1.196 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/1.95e-09f,
        /*load_a_cost=*/3.27e-10f,
        /*load_b_cost=*/1.43e-10f,
        /*output_c=*/1.33e-10f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_BROADWELL_H_
