// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_BROADWELL_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_BROADWELL_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models broadwell = {
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.115, min=0.703, max=1.249 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/1.67e-09f,
        /*load_a_cost=*/1.95e-10f,
        /*load_b_cost=*/4.78e-11f,
        /*output_c=*/5.99e-11f,
    },
    // Ratio (predicted / actual): std=0.108, min=0.753, max=1.227 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/7.82e-10f,
        /*load_a_cost=*/2.04e-10f,
        /*load_b_cost=*/9.21e-11f,
        /*output_c=*/1.46e-10f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.095, min=0.756, max=1.202 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.17e-10f,
        /*load_b_cost=*/6.43e-11f,
        /*output_c=*/7.60e-11f,
    },
    // Ratio (predicted / actual): std=0.046, min=0.745, max=1.112 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/1.26e-09f,
        /*load_a_cost=*/6.28e-10f,
        /*load_b_cost=*/5.13e-11f,
        /*output_c=*/5.90e-11f,
    },
    // Ratio (predicted / actual): std=0.043, min=0.895, max=1.092 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/1.67e-09f,
        /*load_a_cost=*/1.03e-11f,
        /*load_b_cost=*/1.47e-10f,
        /*output_c=*/1.01e-09f,
    },
    // Ratio (predicted / actual): std=0.099, min=0.725, max=1.221 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/4.58e-09f,
        /*load_a_cost=*/1.09e-10f,
        /*load_b_cost=*/4.33e-11f,
        /*output_c=*/8.27e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.096, min=0.842, max=1.209 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/7.97e-10f,
        /*load_a_cost=*/1.98e-10f,
        /*load_b_cost=*/2.14e-11f,
        /*output_c=*/7.25e-11f,
    },
    // Ratio (predicted / actual): std=0.033, min=0.847, max=1.058 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.36e-10f,
        /*load_b_cost=*/2.91e-11f,
        /*output_c=*/1.74e-10f,
    },
    // Ratio (predicted / actual): std=0.067, min=0.817, max=1.205 (n=100)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.88e-10f,
        /*load_b_cost=*/6.58e-11f,
        /*output_c=*/9.44e-11f,
    },
    // Ratio (predicted / actual): std=0.025, min=0.900, max=1.046 (n=60)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.10e-10f,
        /*load_b_cost=*/4.40e-12f,
        /*output_c=*/1.39e-10f,
    },
    // Ratio (predicted / actual): std=0.088, min=0.741, max=1.127 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.10e-11f,
        /*load_b_cost=*/3.24e-11f,
        /*output_c=*/1.97e-10f,
    },
    // Ratio (predicted / actual): std=0.140, min=0.708, max=1.339 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/1.05e-09f,
        /*load_a_cost=*/1.36e-10f,
        /*load_b_cost=*/6.68e-11f,
        /*output_c=*/2.20e-10f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.097, min=0.654, max=1.210 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/3.37e-09f,
        /*load_a_cost=*/2.53e-10f,
        /*load_b_cost=*/6.33e-11f,
        /*output_c=*/3.97e-11f,
    },
    // Ratio (predicted / actual): std=0.094, min=0.678, max=1.187 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/3.59e-09f,
        /*load_a_cost=*/2.53e-10f,
        /*load_b_cost=*/1.24e-10f,
        /*output_c=*/6.81e-11f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.049, min=0.864, max=1.214 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/1.99e-09f,
        /*load_a_cost=*/1.16e-09f,
        /*load_b_cost=*/1.62e-11f,
        /*output_c=*/2.64e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.094, min=0.803, max=1.208 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/1.68e-09f,
        /*load_a_cost=*/1.12e-09f,
        /*load_b_cost=*/4.14e-11f,
        /*output_c=*/5.20e-11f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.106, min=0.749, max=1.222 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/2.30e-09f,
        /*load_a_cost=*/3.19e-10f,
        /*load_b_cost=*/1.51e-10f,
        /*output_c=*/1.25e-10f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_BROADWELL_H_
