// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CASCADE_LAKE_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CASCADE_LAKE_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models cascade_lake = {
#ifdef YNN_ARCH_X86_AVX512VNNI
    // Ratio (predicted / actual): std=0.031, min=0.907, max=1.093 (n=59)
    .x86_avx512vnni_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.24e-10f,
        /*load_b_cost=*/2.98e-12f,
        /*output_c=*/2.18e-11f,
    },
    // Ratio (predicted / actual): std=0.071, min=0.775, max=1.122 (n=140)
    .x86_avx512vnni_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.79e-11f,
        /*load_b_cost=*/1.17e-11f,
        /*output_c=*/6.35e-11f,
    },
    // Ratio (predicted / actual): std=0.101, min=0.569, max=1.218 (n=238)
    .x86_avx512vnni_uint8_int8_int32 = {
        /*block_overhead=*/3.37e-10f,
        /*load_a_cost=*/6.08e-11f,
        /*load_b_cost=*/5.04e-12f,
        /*output_c=*/3.34e-11f,
    },
    // Ratio (predicted / actual): std=0.083, min=0.796, max=1.123 (n=80)
    .x86_avx512vnni_uint8_int8_int32_k16 = {
        /*block_overhead=*/2.83e-09f,
        /*load_a_cost=*/1.12e-11f,
        /*load_b_cost=*/8.39e-12f,
        /*output_c=*/1.52e-10f,
    },
#endif  // YNN_ARCH_X86_AVX512VNNI
#ifdef YNN_ARCH_X86_AVX512
    // Ratio (predicted / actual): std=0.118, min=0.636, max=1.225 (n=258)
    .x86_avx512_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.98e-10f,
        /*load_b_cost=*/2.04e-11f,
        /*output_c=*/3.50e-11f,
    },
    // Ratio (predicted / actual): std=0.089, min=0.612, max=1.201 (n=260)
    .x86_avx512_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.38e-10f,
        /*load_b_cost=*/3.28e-11f,
        /*output_c=*/2.99e-11f,
    },
    // Ratio (predicted / actual): std=0.087, min=0.780, max=1.215 (n=180)
    .x86_avx512_fp16_fp16_fp32 = {
        /*block_overhead=*/7.35e-10f,
        /*load_a_cost=*/7.02e-10f,
        /*load_b_cost=*/2.33e-11f,
        /*output_c=*/2.77e-11f,
    },
    // Ratio (predicted / actual): std=0.097, min=0.770, max=1.182 (n=178)
    .x86_avx512_fp32 = {
        /*block_overhead=*/1.21e-09f,
        /*load_a_cost=*/2.34e-10f,
        /*load_b_cost=*/1.87e-11f,
        /*output_c=*/3.06e-11f,
    },
    // Ratio (predicted / actual): std=0.104, min=0.778, max=1.222 (n=140)
    .x86_avx512_fp32_k2 = {
        /*block_overhead=*/1.53e-09f,
        /*load_a_cost=*/1.03e-10f,
        /*load_b_cost=*/2.04e-11f,
        /*output_c=*/8.00e-11f,
    },
    // Ratio (predicted / actual): std=0.100, min=0.809, max=1.216 (n=179)
    .x86_avx512_fp32_k4 = {
        /*block_overhead=*/3.16e-09f,
        /*load_a_cost=*/5.66e-11f,
        /*load_b_cost=*/2.05e-11f,
        /*output_c=*/1.58e-10f,
    },
    // Ratio (predicted / actual): std=0.097, min=0.757, max=1.204 (n=178)
    .x86_avx512_fp64 = {
        /*block_overhead=*/1.26e-09f,
        /*load_a_cost=*/2.30e-10f,
        /*load_b_cost=*/3.70e-11f,
        /*output_c=*/6.47e-11f,
    },
    // Ratio (predicted / actual): std=0.027, min=0.906, max=1.045 (n=20)
    .x86_avx512_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/0.00e+00f,
        /*load_b_cost=*/1.37e-11f,
        /*output_c=*/2.86e-11f,
    },
    // Ratio (predicted / actual): std=0.107, min=0.681, max=1.187 (n=140)
    .x86_avx512_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.10e-10f,
        /*load_b_cost=*/2.24e-11f,
        /*output_c=*/5.49e-11f,
    },
    // Ratio (predicted / actual): std=0.125, min=0.529, max=1.253 (n=140)
    .x86_avx512_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.32e-10f,
        /*load_b_cost=*/4.47e-11f,
        /*output_c=*/3.97e-11f,
    },
    // Ratio (predicted / actual): std=0.116, min=0.673, max=1.188 (n=140)
    .x86_avx512_int8_int8_int32_k16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.86e-11f,
        /*load_b_cost=*/1.96e-11f,
        /*output_c=*/4.35e-10f,
    },
    // Ratio (predicted / actual): std=0.026, min=0.927, max=1.074 (n=56)
    .x86_avx512_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.02e-10f,
        /*load_b_cost=*/3.30e-12f,
        /*output_c=*/6.11e-11f,
    },
    // Ratio (predicted / actual): std=0.118, min=0.759, max=1.247 (n=116)
    .x86_avx512_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/7.62e-11f,
        /*load_b_cost=*/1.74e-11f,
        /*output_c=*/1.16e-10f,
    },
#endif  // YNN_ARCH_X86_AVX512
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.093, min=0.842, max=1.207 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/5.72e-10f,
        /*load_a_cost=*/1.98e-10f,
        /*load_b_cost=*/3.93e-11f,
        /*output_c=*/7.22e-11f,
    },
    // Ratio (predicted / actual): std=0.095, min=0.818, max=1.200 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/3.57e-10f,
        /*load_a_cost=*/2.02e-10f,
        /*load_b_cost=*/7.83e-11f,
        /*output_c=*/1.56e-10f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.123, min=0.641, max=1.224 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.00e-10f,
        /*load_b_cost=*/4.75e-11f,
        /*output_c=*/9.01e-11f,
    },
    // Ratio (predicted / actual): std=0.037, min=0.830, max=1.150 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/1.05e-09f,
        /*load_a_cost=*/5.68e-10f,
        /*load_b_cost=*/4.69e-11f,
        /*output_c=*/5.20e-11f,
    },
    // Ratio (predicted / actual): std=0.037, min=0.921, max=1.112 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/5.00e-10f,
        /*load_a_cost=*/1.77e-11f,
        /*load_b_cost=*/8.20e-11f,
        /*output_c=*/1.20e-09f,
    },
    // Ratio (predicted / actual): std=0.086, min=0.762, max=1.255 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/3.64e-09f,
        /*load_a_cost=*/9.97e-11f,
        /*load_b_cost=*/3.83e-11f,
        /*output_c=*/8.91e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.096, min=0.867, max=1.251 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/5.60e-10f,
        /*load_a_cost=*/1.75e-10f,
        /*load_b_cost=*/2.07e-11f,
        /*output_c=*/7.39e-11f,
    },
    // Ratio (predicted / actual): std=0.056, min=0.875, max=1.121 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.33e-10f,
        /*load_b_cost=*/3.38e-11f,
        /*output_c=*/1.52e-10f,
    },
    // Ratio (predicted / actual): std=0.066, min=0.685, max=1.171 (n=100)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.98e-10f,
        /*load_b_cost=*/6.13e-11f,
        /*output_c=*/8.31e-11f,
    },
    // Ratio (predicted / actual): std=0.043, min=0.925, max=1.085 (n=60)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/4.04e-09f,
        /*load_a_cost=*/3.83e-10f,
        /*load_b_cost=*/4.81e-12f,
        /*output_c=*/1.60e-10f,
    },
    // Ratio (predicted / actual): std=0.080, min=0.838, max=1.115 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.40e-11f,
        /*load_b_cost=*/2.93e-11f,
        /*output_c=*/1.90e-10f,
    },
    // Ratio (predicted / actual): std=0.131, min=0.752, max=1.325 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/1.83e-09f,
        /*load_a_cost=*/1.35e-10f,
        /*load_b_cost=*/7.07e-11f,
        /*output_c=*/1.57e-10f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.103, min=0.786, max=1.212 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/1.81e-09f,
        /*load_a_cost=*/2.69e-10f,
        /*load_b_cost=*/6.14e-11f,
        /*output_c=*/5.87e-11f,
    },
    // Ratio (predicted / actual): std=0.097, min=0.797, max=1.216 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/1.57e-09f,
        /*load_a_cost=*/2.71e-10f,
        /*load_b_cost=*/1.25e-10f,
        /*output_c=*/1.29e-10f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.045, min=0.907, max=1.157 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/1.76e-09f,
        /*load_a_cost=*/8.67e-10f,
        /*load_b_cost=*/1.50e-11f,
        /*output_c=*/3.89e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.065, min=0.882, max=1.171 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/1.41e-09f,
        /*load_a_cost=*/8.39e-10f,
        /*load_b_cost=*/4.68e-11f,
        /*output_c=*/5.58e-11f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.115, min=0.742, max=1.193 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/1.51e-09f,
        /*load_a_cost=*/3.44e-10f,
        /*load_b_cost=*/1.29e-10f,
        /*output_c=*/1.17e-10f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CASCADE_LAKE_H_
