// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A715_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A715_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models cortex_a715 = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.071, min=0.785, max=1.118 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.08e-11f,
        /*load_b_cost=*/6.32e-11f,
        /*output_c=*/1.13e-10f,
    },
    // Ratio (predicted / actual): std=0.137, min=0.689, max=1.218 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.24e-11f,
        /*load_b_cost=*/5.53e-11f,
        /*output_c=*/1.16e-10f,
    },
    // Ratio (predicted / actual): std=0.185, min=0.700, max=1.340 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.67e-11f,
        /*load_b_cost=*/1.34e-11f,
        /*output_c=*/1.10e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.184, min=0.702, max=1.329 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.39e-11f,
        /*load_b_cost=*/2.66e-11f,
        /*output_c=*/1.09e-10f,
    },
    // Ratio (predicted / actual): std=0.119, min=0.767, max=1.225 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/1.14e-09f,
        /*load_a_cost=*/1.87e-10f,
        /*load_b_cost=*/4.37e-11f,
        /*output_c=*/4.39e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.192, min=0.678, max=1.370 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.95e-10f,
        /*load_b_cost=*/9.00e-11f,
        /*output_c=*/1.09e-10f,
    },
    // Ratio (predicted / actual): std=0.194, min=0.683, max=1.400 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.00e-10f,
        /*load_b_cost=*/1.80e-10f,
        /*output_c=*/1.69e-10f,
    },
    // Ratio (predicted / actual): std=0.128, min=0.789, max=1.260 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.77e-10f,
        /*load_b_cost=*/1.48e-10f,
        /*output_c=*/8.30e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.125, min=0.755, max=1.164 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.78e-11f,
        /*load_b_cost=*/3.39e-11f,
        /*output_c=*/6.65e-11f,
    },
    // Ratio (predicted / actual): std=0.148, min=0.713, max=1.285 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.52e-11f,
        /*load_b_cost=*/5.29e-11f,
        /*output_c=*/5.49e-11f,
    },
    // Ratio (predicted / actual): std=0.222, min=0.689, max=1.423 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.35e-11f,
        /*load_b_cost=*/2.21e-11f,
        /*output_c=*/9.79e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.172, min=0.727, max=1.329 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.68e-10f,
        /*load_b_cost=*/1.96e-10f,
        /*output_c=*/1.57e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A715_H_
