// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_X1_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_X1_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models cortex_x1 = {
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.126, min=0.784, max=1.282 (n=200)
    .arm64_neon_fp32 = {
        /*block_overhead=*/1.17e-10f,
        /*load_a_cost=*/1.37e-10f,
        /*load_b_cost=*/5.25e-11f,
        /*output_c=*/6.13e-11f,
    },
    // Ratio (predicted / actual): std=0.139, min=0.778, max=1.307 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/1.30e-10f,
        /*load_a_cost=*/1.29e-10f,
        /*load_b_cost=*/1.08e-10f,
        /*output_c=*/1.25e-10f,
    },
    // Ratio (predicted / actual): std=0.129, min=0.777, max=1.227 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.74e-10f,
        /*load_b_cost=*/8.69e-11f,
        /*output_c=*/8.42e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.107, min=0.797, max=1.164 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.56e-11f,
        /*load_b_cost=*/2.00e-11f,
        /*output_c=*/8.72e-11f,
    },
    // Ratio (predicted / actual): std=0.144, min=0.735, max=1.236 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.81e-11f,
        /*load_b_cost=*/2.65e-11f,
        /*output_c=*/5.76e-11f,
    },
    // Ratio (predicted / actual): std=0.174, min=0.721, max=1.360 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.22e-11f,
        /*load_b_cost=*/1.30e-11f,
        /*output_c=*/7.85e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.138, min=0.813, max=1.254 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.12e-10f,
        /*load_b_cost=*/1.30e-10f,
        /*output_c=*/1.37e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_X1_H_
