// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_X4_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_X4_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models cortex_x4 = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.114, min=0.665, max=1.272 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.65e-11f,
        /*load_b_cost=*/1.75e-11f,
        /*output_c=*/6.61e-11f,
    },
    // Ratio (predicted / actual): std=0.187, min=0.559, max=1.299 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.02e-11f,
        /*load_b_cost=*/2.34e-11f,
        /*output_c=*/8.17e-11f,
    },
    // Ratio (predicted / actual): std=0.146, min=0.739, max=1.312 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.15e-11f,
        /*load_b_cost=*/1.17e-11f,
        /*output_c=*/8.40e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.153, min=0.808, max=1.326 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.17e-11f,
        /*load_b_cost=*/2.74e-11f,
        /*output_c=*/9.03e-11f,
    },
    // Ratio (predicted / actual): std=0.109, min=0.802, max=1.180 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/7.51e-10f,
        /*load_a_cost=*/1.57e-10f,
        /*load_b_cost=*/4.06e-11f,
        /*output_c=*/3.21e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.094, min=0.839, max=1.196 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.93e-10f,
        /*load_b_cost=*/7.81e-11f,
        /*output_c=*/6.88e-11f,
    },
    // Ratio (predicted / actual): std=0.107, min=0.801, max=1.277 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.75e-10f,
        /*load_b_cost=*/1.67e-10f,
        /*output_c=*/1.13e-10f,
    },
    // Ratio (predicted / actual): std=0.143, min=0.766, max=1.258 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.07e-10f,
        /*load_b_cost=*/1.13e-10f,
        /*output_c=*/6.56e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.109, min=0.775, max=1.161 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.40e-11f,
        /*load_b_cost=*/2.41e-11f,
        /*output_c=*/7.54e-11f,
    },
    // Ratio (predicted / actual): std=0.165, min=0.718, max=1.308 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.48e-11f,
        /*load_b_cost=*/3.03e-11f,
        /*output_c=*/5.75e-11f,
    },
    // Ratio (predicted / actual): std=0.142, min=0.668, max=1.308 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.48e-11f,
        /*load_b_cost=*/1.83e-11f,
        /*output_c=*/6.23e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.166, min=0.771, max=1.373 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.59e-10f,
        /*load_b_cost=*/1.70e-10f,
        /*output_c=*/1.66e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_X4_H_
