// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A710_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A710_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models cortex_a710 = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.072, min=0.764, max=1.159 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.05e-11f,
        /*load_b_cost=*/6.36e-11f,
        /*output_c=*/1.11e-10f,
    },
    // Ratio (predicted / actual): std=0.170, min=0.606, max=1.240 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.22e-11f,
        /*load_b_cost=*/5.76e-11f,
        /*output_c=*/1.18e-10f,
    },
    // Ratio (predicted / actual): std=0.175, min=0.707, max=1.299 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.59e-11f,
        /*load_b_cost=*/1.38e-11f,
        /*output_c=*/1.11e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.173, min=0.711, max=1.305 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.26e-11f,
        /*load_b_cost=*/2.72e-11f,
        /*output_c=*/1.23e-10f,
    },
    // Ratio (predicted / actual): std=0.098, min=0.827, max=1.169 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/4.56e-10f,
        /*load_a_cost=*/2.33e-10f,
        /*load_b_cost=*/4.35e-11f,
        /*output_c=*/4.48e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.186, min=0.678, max=1.324 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.92e-10f,
        /*load_b_cost=*/9.13e-11f,
        /*output_c=*/1.07e-10f,
    },
    // Ratio (predicted / actual): std=0.189, min=0.685, max=1.343 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/6.35e-11f,
        /*load_a_cost=*/1.98e-10f,
        /*load_b_cost=*/1.81e-10f,
        /*output_c=*/1.67e-10f,
    },
    // Ratio (predicted / actual): std=0.133, min=0.782, max=1.258 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.28e-10f,
        /*load_b_cost=*/1.82e-10f,
        /*output_c=*/4.80e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.126, min=0.754, max=1.167 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.84e-11f,
        /*load_b_cost=*/3.29e-11f,
        /*output_c=*/7.24e-11f,
    },
    // Ratio (predicted / actual): std=0.146, min=0.759, max=1.283 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.26e-11f,
        /*load_b_cost=*/5.32e-11f,
        /*output_c=*/4.89e-11f,
    },
    // Ratio (predicted / actual): std=0.220, min=0.698, max=1.418 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.31e-11f,
        /*load_b_cost=*/2.22e-11f,
        /*output_c=*/9.68e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.164, min=0.741, max=1.314 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.58e-10f,
        /*load_b_cost=*/2.02e-10f,
        /*output_c=*/1.69e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A710_H_
