// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A510_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A510_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models cortex_a510 = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.123, min=0.676, max=1.257 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.41e-11f,
        /*load_b_cost=*/7.51e-11f,
        /*output_c=*/3.96e-10f,
    },
    // Ratio (predicted / actual): std=0.175, min=0.627, max=1.356 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/7.98e-11f,
        /*load_b_cost=*/7.74e-11f,
        /*output_c=*/4.28e-10f,
    },
    // Ratio (predicted / actual): std=0.182, min=0.681, max=1.361 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.62e-11f,
        /*load_b_cost=*/3.89e-11f,
        /*output_c=*/3.96e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.190, min=0.698, max=1.379 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.88e-10f,
        /*load_b_cost=*/1.18e-10f,
        /*output_c=*/4.54e-10f,
    },
    // Ratio (predicted / actual): std=0.079, min=0.728, max=1.238 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/1.69e-08f,
        /*load_a_cost=*/4.28e-10f,
        /*load_b_cost=*/1.56e-10f,
        /*output_c=*/5.66e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.196, min=0.701, max=1.428 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/2.40e-09f,
        /*load_a_cost=*/3.78e-10f,
        /*load_b_cost=*/2.34e-10f,
        /*output_c=*/5.79e-10f,
    },
    // Ratio (predicted / actual): std=0.123, min=0.762, max=1.338 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/4.19e-09f,
        /*load_a_cost=*/4.45e-10f,
        /*load_b_cost=*/6.24e-10f,
        /*output_c=*/7.11e-10f,
    },
    // Ratio (predicted / actual): std=0.118, min=0.784, max=1.304 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/5.76e-09f,
        /*load_a_cost=*/3.91e-10f,
        /*load_b_cost=*/2.92e-10f,
        /*output_c=*/4.73e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.120, min=0.776, max=1.244 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.00e-10f,
        /*load_b_cost=*/6.65e-11f,
        /*output_c=*/4.76e-10f,
    },
    // Ratio (predicted / actual): std=0.150, min=0.756, max=1.289 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.88e-10f,
        /*load_b_cost=*/6.97e-11f,
        /*output_c=*/3.68e-10f,
    },
    // Ratio (predicted / actual): std=0.154, min=0.595, max=1.323 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/6.74e-10f,
        /*load_a_cost=*/1.29e-10f,
        /*load_b_cost=*/6.47e-11f,
        /*output_c=*/4.32e-10f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.157, min=0.714, max=1.335 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.97e-10f,
        /*load_b_cost=*/3.05e-10f,
        /*output_c=*/7.06e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A510_H_
