// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A725_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A725_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models cortex_a725 = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.071, min=0.793, max=1.107 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.91e-11f,
        /*load_b_cost=*/5.83e-11f,
        /*output_c=*/1.01e-10f,
    },
    // Ratio (predicted / actual): std=0.137, min=0.680, max=1.206 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.07e-11f,
        /*load_b_cost=*/5.10e-11f,
        /*output_c=*/1.03e-10f,
    },
    // Ratio (predicted / actual): std=0.186, min=0.702, max=1.323 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.46e-11f,
        /*load_b_cost=*/1.23e-11f,
        /*output_c=*/1.02e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.182, min=0.685, max=1.329 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.95e-11f,
        /*load_b_cost=*/2.45e-11f,
        /*output_c=*/1.01e-10f,
    },
    // Ratio (predicted / actual): std=0.122, min=0.710, max=1.291 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/1.17e-09f,
        /*load_a_cost=*/1.78e-10f,
        /*load_b_cost=*/4.05e-11f,
        /*output_c=*/3.65e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.192, min=0.673, max=1.380 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.84e-10f,
        /*load_b_cost=*/8.74e-11f,
        /*output_c=*/9.59e-11f,
    },
    // Ratio (predicted / actual): std=0.196, min=0.680, max=1.394 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.93e-10f,
        /*load_b_cost=*/1.72e-10f,
        /*output_c=*/1.59e-10f,
    },
    // Ratio (predicted / actual): std=0.133, min=0.791, max=1.324 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.55e-10f,
        /*load_b_cost=*/1.42e-10f,
        /*output_c=*/7.90e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.126, min=0.758, max=1.170 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.31e-11f,
        /*load_b_cost=*/3.12e-11f,
        /*output_c=*/6.26e-11f,
    },
    // Ratio (predicted / actual): std=0.144, min=0.749, max=1.255 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.07e-11f,
        /*load_b_cost=*/4.86e-11f,
        /*output_c=*/4.13e-11f,
    },
    // Ratio (predicted / actual): std=0.231, min=0.647, max=1.475 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.35e-11f,
        /*load_b_cost=*/2.12e-11f,
        /*output_c=*/9.20e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.169, min=0.710, max=1.360 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.23e-10f,
        /*load_b_cost=*/1.94e-10f,
        /*output_c=*/1.56e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_CORTEX_A725_H_
