// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_EVEREST_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_EVEREST_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models everest = {
#ifndef YNN_DISABLE_SME
#ifdef YNN_ARCH_ARM64_SME2
    // Ratio (predicted / actual): std=0.034, min=0.952, max=1.083 (n=14)
    .arm64_sme2_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/7.51e-12f,
        /*load_b_cost=*/7.51e-12f,
        /*output_c=*/1.19e-11f,
    },
    // Ratio (predicted / actual): std=0.074, min=0.863, max=1.127 (n=14)
    .arm64_sme2_bf16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.61e-12f,
        /*load_b_cost=*/8.61e-12f,
        /*output_c=*/9.07e-12f,
    },
    // Ratio (predicted / actual): std=0.057, min=0.918, max=1.129 (n=14)
    .arm64_sme2_fp16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.91e-12f,
        /*load_b_cost=*/8.91e-12f,
        /*output_c=*/9.36e-12f,
    },
    // Ratio (predicted / actual): std=0.096, min=0.841, max=1.200 (n=14)
    .arm64_sme2_int8 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.44e-12f,
        /*load_b_cost=*/4.44e-12f,
        /*output_c=*/7.82e-12f,
    },
#endif  // YNN_ARCH_ARM64_SME2
#ifdef YNN_ARCH_ARM64_SME
    // Ratio (predicted / actual): std=0.027, min=0.946, max=1.044 (n=14)
    .arm64_sme_fp32 = {
        /*block_overhead=*/1.10e-08f,
        /*load_a_cost=*/1.08e-11f,
        /*load_b_cost=*/1.08e-11f,
        /*output_c=*/0.00e+00f,
    },
    // Ratio (predicted / actual): std=0.045, min=0.925, max=1.073 (n=14)
    .arm64_sme_bf16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.93e-12f,
        /*load_b_cost=*/8.93e-12f,
        /*output_c=*/8.79e-12f,
    },
    // Ratio (predicted / actual): std=0.052, min=0.917, max=1.089 (n=14)
    .arm64_sme_fp16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.59e-12f,
        /*load_b_cost=*/8.59e-12f,
        /*output_c=*/8.91e-12f,
    },
    // Ratio (predicted / actual): std=0.072, min=0.901, max=1.145 (n=14)
    .arm64_sme_int4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.85e-12f,
        /*load_b_cost=*/4.85e-12f,
        /*output_c=*/7.79e-12f,
    },
    // Ratio (predicted / actual): std=0.072, min=0.901, max=1.144 (n=14)
    .arm64_sme_int2 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.72e-12f,
        /*load_b_cost=*/5.72e-12f,
        /*output_c=*/5.99e-12f,
    },
#endif  // YNN_ARCH_ARM64_SME
#endif  // YNN_DISABLE_SME
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.143, min=0.732, max=1.514 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.77e-11f,
        /*load_b_cost=*/1.91e-11f,
        /*output_c=*/2.41e-11f,
    },
    // Ratio (predicted / actual): std=0.168, min=0.784, max=1.526 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.77e-11f,
        /*load_b_cost=*/1.88e-11f,
        /*output_c=*/2.59e-11f,
    },
    // Ratio (predicted / actual): std=0.203, min=0.658, max=1.437 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.83e-11f,
        /*load_b_cost=*/9.34e-12f,
        /*output_c=*/2.84e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.219, min=0.605, max=1.373 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.43e-10f,
        /*load_b_cost=*/6.72e-11f,
        /*output_c=*/3.59e-11f,
    },
    // Ratio (predicted / actual): std=0.148, min=0.737, max=1.208 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.51e-10f,
        /*load_b_cost=*/5.59e-11f,
        /*output_c=*/5.21e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.147, min=0.726, max=1.577 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.03e-10f,
        /*load_b_cost=*/3.25e-11f,
        /*output_c=*/1.63e-11f,
    },
    // Ratio (predicted / actual): std=0.154, min=0.729, max=1.520 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.07e-10f,
        /*load_b_cost=*/5.93e-11f,
        /*output_c=*/5.13e-11f,
    },
    // Ratio (predicted / actual): std=0.116, min=0.774, max=1.332 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.11e-10f,
        /*load_b_cost=*/4.65e-11f,
        /*output_c=*/1.35e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.145, min=0.537, max=1.336 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.21e-11f,
        /*load_b_cost=*/1.29e-11f,
        /*output_c=*/0.00e+00f,
    },
    // Ratio (predicted / actual): std=0.172, min=0.655, max=1.377 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.26e-11f,
        /*load_b_cost=*/1.51e-11f,
        /*output_c=*/1.82e-11f,
    },
    // Ratio (predicted / actual): std=0.173, min=0.701, max=1.484 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.36e-11f,
        /*load_b_cost=*/6.92e-12f,
        /*output_c=*/3.55e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.161, min=0.558, max=1.427 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/9.77e-11f,
        /*load_b_cost=*/4.62e-11f,
        /*output_c=*/2.03e-11f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_EVEREST_H_
