// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_GOLDEN_COVE_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_GOLDEN_COVE_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models golden_cove = {
#ifdef YNN_ARCH_X86_AMXBF16
    // Ratio (predicted / actual): std=0.065, min=0.901, max=1.106 (n=15)
    .x86_amx_bf16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.03e-11f,
        /*load_b_cost=*/1.03e-11f,
        /*output_c=*/3.05e-11f,
    },
#endif  // YNN_ARCH_X86_AMXBF16
#ifdef YNN_ARCH_X86_AMXINT8
    // Ratio (predicted / actual): std=0.049, min=0.907, max=1.094 (n=22)
    .x86_amx_int8 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.74e-12f,
        /*load_b_cost=*/4.74e-12f,
        /*output_c=*/3.46e-11f,
    },
    // Ratio (predicted / actual): std=0.049, min=0.907, max=1.094 (n=22)
    .x86_amx_uint8 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.74e-12f,
        /*load_b_cost=*/4.74e-12f,
        /*output_c=*/3.46e-11f,
    },
#endif  // YNN_ARCH_X86_AMXINT8
#ifdef YNN_ARCH_X86_AVX512VNNI
    // Ratio (predicted / actual): std=0.023, min=0.910, max=1.108 (n=59)
    .x86_avx512vnni_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.80e-10f,
        /*load_b_cost=*/2.99e-12f,
        /*output_c=*/0.00e+00f,
    },
    // Ratio (predicted / actual): std=0.078, min=0.806, max=1.141 (n=140)
    .x86_avx512vnni_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.98e-11f,
        /*load_b_cost=*/1.03e-11f,
        /*output_c=*/3.22e-11f,
    },
    // Ratio (predicted / actual): std=0.150, min=0.604, max=1.451 (n=238)
    .x86_avx512vnni_uint8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.07e-11f,
        /*load_b_cost=*/4.51e-12f,
        /*output_c=*/1.60e-11f,
    },
    // Ratio (predicted / actual): std=0.089, min=0.738, max=1.204 (n=80)
    .x86_avx512vnni_uint8_int8_int32_k16 = {
        /*block_overhead=*/1.08e-09f,
        /*load_a_cost=*/9.23e-12f,
        /*load_b_cost=*/7.14e-12f,
        /*output_c=*/8.26e-11f,
    },
#endif  // YNN_ARCH_X86_AVX512VNNI
#ifdef YNN_ARCH_X86_AVXVNNI
    // Ratio (predicted / actual): std=0.054, min=0.887, max=1.170 (n=60)
    .x86_avxvnni_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.49e-11f,
        /*load_b_cost=*/1.45e-11f,
        /*output_c=*/2.91e-11f,
    },
    // Ratio (predicted / actual): std=0.094, min=0.748, max=1.134 (n=80)
    .x86_avxvnni_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.73e-11f,
        /*load_b_cost=*/1.44e-11f,
        /*output_c=*/8.94e-11f,
    },
    // Ratio (predicted / actual): std=0.128, min=0.751, max=1.347 (n=120)
    .x86_avxvnni_uint8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.40e-11f,
        /*load_b_cost=*/7.12e-12f,
        /*output_c=*/3.61e-11f,
    },
#endif  // YNN_ARCH_X86_AVXVNNI
#ifdef YNN_ARCH_X86_AVX512BF16
    // Ratio (predicted / actual): std=0.219, min=0.539, max=1.497 (n=258)
    .x86_avx512bf16_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.69e-10f,
        /*load_b_cost=*/2.78e-11f,
        /*output_c=*/1.65e-11f,
    },
#endif  // YNN_ARCH_X86_AVX512BF16
#ifdef YNN_ARCH_X86_AVX512
    // Ratio (predicted / actual): std=0.134, min=0.686, max=1.325 (n=258)
    .x86_avx512_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.53e-10f,
        /*load_b_cost=*/2.19e-11f,
        /*output_c=*/1.36e-11f,
    },
    // Ratio (predicted / actual): std=0.098, min=0.727, max=1.240 (n=260)
    .x86_avx512_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.55e-10f,
        /*load_b_cost=*/2.86e-11f,
        /*output_c=*/1.16e-11f,
    },
    // Ratio (predicted / actual): std=0.089, min=0.819, max=1.182 (n=180)
    .x86_avx512_fp16_fp16_fp32 = {
        /*block_overhead=*/1.38e-10f,
        /*load_a_cost=*/6.21e-10f,
        /*load_b_cost=*/3.19e-11f,
        /*output_c=*/9.75e-12f,
    },
    // Ratio (predicted / actual): std=0.122, min=0.635, max=1.235 (n=178)
    .x86_avx512_fp32 = {
        /*block_overhead=*/7.12e-11f,
        /*load_a_cost=*/1.88e-10f,
        /*load_b_cost=*/1.65e-11f,
        /*output_c=*/2.02e-11f,
    },
    // Ratio (predicted / actual): std=0.134, min=0.620, max=1.242 (n=140)
    .x86_avx512_fp32_k2 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.43e-11f,
        /*load_b_cost=*/1.78e-11f,
        /*output_c=*/5.90e-11f,
    },
    // Ratio (predicted / actual): std=0.126, min=0.726, max=1.265 (n=179)
    .x86_avx512_fp32_k4 = {
        /*block_overhead=*/5.19e-10f,
        /*load_a_cost=*/4.36e-11f,
        /*load_b_cost=*/1.90e-11f,
        /*output_c=*/1.41e-10f,
    },
    // Ratio (predicted / actual): std=0.118, min=0.692, max=1.239 (n=178)
    .x86_avx512_fp64 = {
        /*block_overhead=*/2.55e-10f,
        /*load_a_cost=*/1.83e-10f,
        /*load_b_cost=*/3.31e-11f,
        /*output_c=*/3.97e-11f,
    },
    // Ratio (predicted / actual): std=0.031, min=0.954, max=1.102 (n=20)
    .x86_avx512_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/0.00e+00f,
        /*load_b_cost=*/1.10e-11f,
        /*output_c=*/3.61e-12f,
    },
    // Ratio (predicted / actual): std=0.108, min=0.800, max=1.242 (n=140)
    .x86_avx512_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.70e-10f,
        /*load_b_cost=*/1.95e-11f,
        /*output_c=*/3.27e-11f,
    },
    // Ratio (predicted / actual): std=0.108, min=0.592, max=1.245 (n=140)
    .x86_avx512_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.43e-10f,
        /*load_b_cost=*/3.77e-11f,
        /*output_c=*/1.09e-11f,
    },
    // Ratio (predicted / actual): std=0.125, min=0.730, max=1.178 (n=140)
    .x86_avx512_int8_int8_int32_k16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.85e-11f,
        /*load_b_cost=*/1.77e-11f,
        /*output_c=*/3.03e-10f,
    },
    // Ratio (predicted / actual): std=0.015, min=0.929, max=1.021 (n=56)
    .x86_avx512_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.24e-10f,
        /*load_b_cost=*/3.75e-12f,
        /*output_c=*/8.63e-13f,
    },
    // Ratio (predicted / actual): std=0.117, min=0.727, max=1.176 (n=116)
    .x86_avx512_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.21e-11f,
        /*load_b_cost=*/1.55e-11f,
        /*output_c=*/5.90e-11f,
    },
#endif  // YNN_ARCH_X86_AVX512
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.125, min=0.730, max=1.324 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/1.54e-10f,
        /*load_a_cost=*/1.61e-10f,
        /*load_b_cost=*/2.74e-11f,
        /*output_c=*/4.01e-11f,
    },
    // Ratio (predicted / actual): std=0.126, min=0.710, max=1.305 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/1.30e-10f,
        /*load_a_cost=*/1.57e-10f,
        /*load_b_cost=*/5.53e-11f,
        /*output_c=*/7.90e-11f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.125, min=0.737, max=1.399 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.13e-10f,
        /*load_b_cost=*/4.15e-11f,
        /*output_c=*/3.73e-11f,
    },
    // Ratio (predicted / actual): std=0.049, min=0.874, max=1.161 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/4.82e-10f,
        /*load_a_cost=*/3.19e-10f,
        /*load_b_cost=*/4.24e-11f,
        /*output_c=*/3.30e-11f,
    },
    // Ratio (predicted / actual): std=0.039, min=0.923, max=1.080 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/7.86e-10f,
        /*load_a_cost=*/1.45e-11f,
        /*load_b_cost=*/5.33e-11f,
        /*output_c=*/6.20e-10f,
    },
    // Ratio (predicted / actual): std=0.111, min=0.798, max=1.297 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/1.85e-09f,
        /*load_a_cost=*/8.02e-11f,
        /*load_b_cost=*/2.57e-11f,
        /*output_c=*/5.41e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.095, min=0.865, max=1.212 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/1.99e-10f,
        /*load_a_cost=*/1.56e-10f,
        /*load_b_cost=*/1.36e-11f,
        /*output_c=*/3.10e-11f,
    },
    // Ratio (predicted / actual): std=0.025, min=0.947, max=1.057 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/9.82e-11f,
        /*load_b_cost=*/2.03e-11f,
        /*output_c=*/8.43e-11f,
    },
    // Ratio (predicted / actual): std=0.047, min=0.817, max=1.149 (n=100)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.64e-10f,
        /*load_b_cost=*/4.06e-11f,
        /*output_c=*/4.17e-11f,
    },
    // Ratio (predicted / actual): std=0.016, min=0.925, max=1.030 (n=60)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.46e-10f,
        /*load_b_cost=*/3.56e-12f,
        /*output_c=*/2.17e-11f,
    },
    // Ratio (predicted / actual): std=0.076, min=0.763, max=1.104 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.46e-11f,
        /*load_b_cost=*/2.13e-11f,
        /*output_c=*/6.52e-11f,
    },
    // Ratio (predicted / actual): std=0.140, min=0.711, max=1.305 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/1.20e-09f,
        /*load_a_cost=*/7.86e-11f,
        /*load_b_cost=*/3.97e-11f,
        /*output_c=*/9.35e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.094, min=0.789, max=1.180 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/1.51e-09f,
        /*load_a_cost=*/1.53e-10f,
        /*load_b_cost=*/3.53e-11f,
        /*output_c=*/2.57e-11f,
    },
    // Ratio (predicted / actual): std=0.091, min=0.785, max=1.162 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/1.50e-09f,
        /*load_a_cost=*/1.52e-10f,
        /*load_b_cost=*/7.11e-11f,
        /*output_c=*/5.06e-11f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.046, min=0.894, max=1.150 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/1.31e-09f,
        /*load_a_cost=*/5.18e-10f,
        /*load_b_cost=*/2.34e-11f,
        /*output_c=*/1.27e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.055, min=0.874, max=1.180 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/1.19e-09f,
        /*load_a_cost=*/6.04e-10f,
        /*load_b_cost=*/4.17e-11f,
        /*output_c=*/9.97e-12f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.111, min=0.779, max=1.232 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/9.76e-10f,
        /*load_a_cost=*/2.36e-10f,
        /*load_b_cost=*/7.50e-11f,
        /*output_c=*/6.69e-11f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_GOLDEN_COVE_H_
