// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_HASWELL_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_HASWELL_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models haswell = {
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.112, min=0.779, max=1.243 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/2.15e-09f,
        /*load_a_cost=*/1.99e-10f,
        /*load_b_cost=*/4.85e-11f,
        /*output_c=*/5.71e-11f,
    },
    // Ratio (predicted / actual): std=0.113, min=0.794, max=1.244 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/1.05e-09f,
        /*load_a_cost=*/2.03e-10f,
        /*load_b_cost=*/9.59e-11f,
        /*output_c=*/1.43e-10f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.103, min=0.755, max=1.204 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.22e-10f,
        /*load_b_cost=*/6.52e-11f,
        /*output_c=*/8.58e-11f,
    },
    // Ratio (predicted / actual): std=0.035, min=0.915, max=1.114 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/1.05e-09f,
        /*load_a_cost=*/6.31e-10f,
        /*load_b_cost=*/5.06e-11f,
        /*output_c=*/6.41e-11f,
    },
    // Ratio (predicted / actual): std=0.031, min=0.914, max=1.099 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/1.40e-09f,
        /*load_a_cost=*/9.27e-12f,
        /*load_b_cost=*/1.53e-10f,
        /*output_c=*/1.11e-09f,
    },
    // Ratio (predicted / actual): std=0.094, min=0.785, max=1.219 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/4.80e-09f,
        /*load_a_cost=*/1.10e-10f,
        /*load_b_cost=*/4.42e-11f,
        /*output_c=*/7.29e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.098, min=0.831, max=1.203 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/3.16e-10f,
        /*load_a_cost=*/1.96e-10f,
        /*load_b_cost=*/2.23e-11f,
        /*output_c=*/8.87e-11f,
    },
    // Ratio (predicted / actual): std=0.023, min=0.939, max=1.064 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.35e-10f,
        /*load_b_cost=*/2.94e-11f,
        /*output_c=*/1.85e-10f,
    },
    // Ratio (predicted / actual): std=0.055, min=0.781, max=1.159 (n=100)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.95e-10f,
        /*load_b_cost=*/6.50e-11f,
        /*output_c=*/9.77e-11f,
    },
    // Ratio (predicted / actual): std=0.017, min=0.949, max=1.036 (n=60)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.22e-10f,
        /*load_b_cost=*/5.44e-12f,
        /*output_c=*/1.62e-10f,
    },
    // Ratio (predicted / actual): std=0.080, min=0.870, max=1.129 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.95e-11f,
        /*load_b_cost=*/3.37e-11f,
        /*output_c=*/2.12e-10f,
    },
    // Ratio (predicted / actual): std=0.131, min=0.721, max=1.326 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/2.24e-09f,
        /*load_a_cost=*/1.35e-10f,
        /*load_b_cost=*/6.95e-11f,
        /*output_c=*/1.82e-10f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.086, min=0.796, max=1.202 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/3.02e-09f,
        /*load_a_cost=*/2.56e-10f,
        /*load_b_cost=*/6.39e-11f,
        /*output_c=*/4.85e-11f,
    },
    // Ratio (predicted / actual): std=0.087, min=0.797, max=1.194 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/3.08e-09f,
        /*load_a_cost=*/2.55e-10f,
        /*load_b_cost=*/1.27e-10f,
        /*output_c=*/8.66e-11f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.042, min=0.904, max=1.200 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/2.10e-09f,
        /*load_a_cost=*/1.19e-09f,
        /*load_b_cost=*/1.19e-11f,
        /*output_c=*/2.83e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.093, min=0.780, max=1.202 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/1.35e-09f,
        /*load_a_cost=*/1.10e-09f,
        /*load_b_cost=*/4.46e-11f,
        /*output_c=*/5.43e-11f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.107, min=0.751, max=1.186 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/2.44e-09f,
        /*load_a_cost=*/3.04e-10f,
        /*load_b_cost=*/1.24e-10f,
        /*output_c=*/9.67e-11f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_HASWELL_H_
