// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_LUMEX_C1_PRO_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_LUMEX_C1_PRO_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models lumex_c1_pro = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.076, min=0.780, max=1.132 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.97e-11f,
        /*load_b_cost=*/4.29e-11f,
        /*output_c=*/9.51e-11f,
    },
    // Ratio (predicted / actual): std=0.147, min=0.647, max=1.197 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.18e-11f,
        /*load_b_cost=*/3.75e-11f,
        /*output_c=*/9.16e-11f,
    },
    // Ratio (predicted / actual): std=0.185, min=0.699, max=1.320 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.21e-11f,
        /*load_b_cost=*/1.10e-11f,
        /*output_c=*/9.14e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.182, min=0.701, max=1.326 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.46e-11f,
        /*load_b_cost=*/2.20e-11f,
        /*output_c=*/9.00e-11f,
    },
    // Ratio (predicted / actual): std=0.120, min=0.763, max=1.222 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/9.41e-10f,
        /*load_a_cost=*/1.55e-10f,
        /*load_b_cost=*/3.60e-11f,
        /*output_c=*/3.61e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.192, min=0.677, max=1.379 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.62e-10f,
        /*load_b_cost=*/7.43e-11f,
        /*output_c=*/8.82e-11f,
    },
    // Ratio (predicted / actual): std=0.194, min=0.681, max=1.376 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.65e-10f,
        /*load_b_cost=*/1.49e-10f,
        /*output_c=*/1.34e-10f,
    },
    // Ratio (predicted / actual): std=0.144, min=0.772, max=1.249 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.17e-10f,
        /*load_b_cost=*/1.15e-10f,
        /*output_c=*/6.89e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.126, min=0.741, max=1.182 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.84e-11f,
        /*load_b_cost=*/2.74e-11f,
        /*output_c=*/5.44e-11f,
    },
    // Ratio (predicted / actual): std=0.178, min=0.723, max=1.288 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.50e-11f,
        /*load_b_cost=*/3.79e-11f,
        /*output_c=*/4.33e-11f,
    },
    // Ratio (predicted / actual): std=0.224, min=0.697, max=1.426 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.43e-11f,
        /*load_b_cost=*/1.84e-11f,
        /*output_c=*/7.86e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.176, min=0.708, max=1.329 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.04e-10f,
        /*load_b_cost=*/1.71e-10f,
        /*output_c=*/1.45e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_LUMEX_C1_PRO_H_
