// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_LUMEX_C1_ULTRA_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_LUMEX_C1_ULTRA_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models lumex_c1_ultra = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.105, min=0.703, max=1.231 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/9.24e-12f,
        /*load_b_cost=*/1.27e-11f,
        /*output_c=*/5.53e-11f,
    },
    // Ratio (predicted / actual): std=0.165, min=0.613, max=1.304 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.54e-12f,
        /*load_b_cost=*/1.20e-11f,
        /*output_c=*/5.70e-11f,
    },
    // Ratio (predicted / actual): std=0.105, min=0.693, max=1.270 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/9.16e-12f,
        /*load_b_cost=*/4.92e-12f,
        /*output_c=*/5.91e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.126, min=0.823, max=1.246 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.03e-11f,
        /*load_b_cost=*/1.19e-11f,
        /*output_c=*/5.79e-11f,
    },
    // Ratio (predicted / actual): std=0.135, min=0.774, max=1.296 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/2.12e-09f,
        /*load_a_cost=*/1.04e-10f,
        /*load_b_cost=*/1.31e-11f,
        /*output_c=*/0.00e+00f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.133, min=0.797, max=1.345 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.36e-10f,
        /*load_b_cost=*/5.54e-11f,
        /*output_c=*/6.67e-11f,
    },
    // Ratio (predicted / actual): std=0.105, min=0.776, max=1.294 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/2.77e-10f,
        /*load_a_cost=*/1.25e-10f,
        /*load_b_cost=*/9.88e-11f,
        /*output_c=*/1.05e-10f,
    },
    // Ratio (predicted / actual): std=0.137, min=0.735, max=1.323 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.24e-10f,
        /*load_b_cost=*/6.52e-11f,
        /*output_c=*/5.43e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.122, min=0.737, max=1.177 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.36e-11f,
        /*load_b_cost=*/1.62e-11f,
        /*output_c=*/7.46e-11f,
    },
    // Ratio (predicted / actual): std=0.171, min=0.643, max=1.330 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.66e-11f,
        /*load_b_cost=*/2.13e-11f,
        /*output_c=*/4.60e-11f,
    },
    // Ratio (predicted / actual): std=0.156, min=0.668, max=1.349 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.00e-11f,
        /*load_b_cost=*/1.02e-11f,
        /*output_c=*/6.90e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.167, min=0.575, max=1.410 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.10e-10f,
        /*load_b_cost=*/9.97e-11f,
        /*output_c=*/3.45e-11f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_LUMEX_C1_ULTRA_H_
