// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_NEOVERSE_N1_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_NEOVERSE_N1_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models neoverse_n1 = {
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.181, min=0.698, max=1.364 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.91e-10f,
        /*load_b_cost=*/8.90e-11f,
        /*output_c=*/2.00e-10f,
    },
    // Ratio (predicted / actual): std=0.200, min=0.670, max=1.393 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.24e-10f,
        /*load_b_cost=*/1.75e-10f,
        /*output_c=*/3.08e-10f,
    },
    // Ratio (predicted / actual): std=0.157, min=0.747, max=1.269 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.78e-10f,
        /*load_b_cost=*/1.60e-10f,
        /*output_c=*/1.64e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.122, min=0.774, max=1.189 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.74e-11f,
        /*load_b_cost=*/3.13e-11f,
        /*output_c=*/1.64e-10f,
    },
    // Ratio (predicted / actual): std=0.157, min=0.769, max=1.235 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/7.82e-11f,
        /*load_b_cost=*/4.74e-11f,
        /*output_c=*/1.13e-10f,
    },
    // Ratio (predicted / actual): std=0.264, min=0.592, max=1.527 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.56e-11f,
        /*load_b_cost=*/2.31e-11f,
        /*output_c=*/1.72e-10f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.183, min=0.782, max=1.437 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.71e-10f,
        /*load_b_cost=*/1.87e-10f,
        /*output_c=*/2.68e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_NEOVERSE_N1_H_
