// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_NEOVERSE_V2_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_NEOVERSE_V2_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models neoverse_v2 = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.084, min=0.791, max=1.161 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.28e-11f,
        /*load_b_cost=*/2.64e-11f,
        /*output_c=*/7.78e-11f,
    },
    // Ratio (predicted / actual): std=0.079, min=0.807, max=1.171 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.26e-11f,
        /*load_b_cost=*/2.58e-11f,
        /*output_c=*/6.77e-11f,
    },
    // Ratio (predicted / actual): std=0.124, min=0.780, max=1.230 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.42e-11f,
        /*load_b_cost=*/9.16e-12f,
        /*output_c=*/6.91e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.129, min=0.779, max=1.232 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.06e-11f,
        /*load_b_cost=*/1.86e-11f,
        /*output_c=*/6.96e-11f,
    },
    // Ratio (predicted / actual): std=0.117, min=0.787, max=1.205 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/8.71e-10f,
        /*load_a_cost=*/1.03e-10f,
        /*load_b_cost=*/2.50e-11f,
        /*output_c=*/3.30e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.103, min=0.801, max=1.215 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.26e-10f,
        /*load_b_cost=*/4.81e-11f,
        /*output_c=*/7.71e-11f,
    },
    // Ratio (predicted / actual): std=0.111, min=0.815, max=1.297 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/1.09e-10f,
        /*load_a_cost=*/1.31e-10f,
        /*load_b_cost=*/9.77e-11f,
        /*output_c=*/1.12e-10f,
    },
    // Ratio (predicted / actual): std=0.148, min=0.733, max=1.248 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.46e-10f,
        /*load_b_cost=*/7.78e-11f,
        /*output_c=*/7.61e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.112, min=0.782, max=1.190 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.26e-11f,
        /*load_b_cost=*/1.76e-11f,
        /*output_c=*/5.73e-11f,
    },
    // Ratio (predicted / actual): std=0.161, min=0.754, max=1.238 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.08e-11f,
        /*load_b_cost=*/2.31e-11f,
        /*output_c=*/5.24e-11f,
    },
    // Ratio (predicted / actual): std=0.181, min=0.672, max=1.371 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.35e-11f,
        /*load_b_cost=*/1.21e-11f,
        /*output_c=*/6.83e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.174, min=0.790, max=1.376 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.36e-10f,
        /*load_b_cost=*/1.15e-10f,
        /*output_c=*/1.04e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_NEOVERSE_V2_H_
