// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ORYON_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ORYON_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models oryon = {
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.102, min=0.729, max=1.255 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/9.67e-12f,
        /*load_b_cost=*/1.49e-11f,
        /*output_c=*/5.05e-11f,
    },
    // Ratio (predicted / actual): std=0.112, min=0.725, max=1.208 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/9.03e-12f,
        /*load_b_cost=*/1.69e-11f,
        /*output_c=*/5.24e-11f,
    },
    // Ratio (predicted / actual): std=0.178, min=0.717, max=1.419 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.07e-11f,
        /*load_b_cost=*/5.57e-12f,
        /*output_c=*/5.33e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.273, min=0.648, max=1.603 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.59e-11f,
        /*load_b_cost=*/2.12e-11f,
        /*output_c=*/5.30e-11f,
    },
    // Ratio (predicted / actual): std=0.164, min=0.674, max=1.314 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/6.10e-10f,
        /*load_a_cost=*/6.85e-11f,
        /*load_b_cost=*/2.00e-11f,
        /*output_c=*/3.83e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.137, min=0.782, max=1.395 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.29e-10f,
        /*load_b_cost=*/4.03e-11f,
        /*output_c=*/6.58e-11f,
    },
    // Ratio (predicted / actual): std=0.184, min=0.640, max=1.386 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/1.15e-09f,
        /*load_a_cost=*/1.36e-10f,
        /*load_b_cost=*/7.40e-11f,
        /*output_c=*/4.71e-11f,
    },
    // Ratio (predicted / actual): std=0.099, min=0.827, max=1.281 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.26e-10f,
        /*load_b_cost=*/5.49e-11f,
        /*output_c=*/6.43e-11f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.127, min=0.815, max=1.177 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.94e-11f,
        /*load_b_cost=*/1.67e-11f,
        /*output_c=*/5.18e-11f,
    },
    // Ratio (predicted / actual): std=0.184, min=0.730, max=1.340 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.79e-11f,
        /*load_b_cost=*/2.19e-11f,
        /*output_c=*/5.86e-11f,
    },
    // Ratio (predicted / actual): std=0.123, min=0.737, max=1.284 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.82e-11f,
        /*load_b_cost=*/1.15e-11f,
        /*output_c=*/6.67e-11f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.150, min=0.648, max=1.285 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.05e-10f,
        /*load_b_cost=*/7.59e-11f,
        /*output_c=*/5.98e-11f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ORYON_H_
