// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_REDWOOD_COVE_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_REDWOOD_COVE_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models redwood_cove = {
#ifdef YNN_ARCH_X86_AMXBF16
    // Ratio (predicted / actual): std=0.075, min=0.843, max=1.113 (n=15)
    .x86_amx_bf16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.92e-12f,
        /*load_b_cost=*/8.62e-12f,
        /*output_c=*/2.25e-11f,
    },
#endif  // YNN_ARCH_X86_AMXBF16
#ifdef YNN_ARCH_X86_AMXFP16
    // Ratio (predicted / actual): std=0.008, min=0.989, max=1.012 (n=5)
    .x86_amx_fp16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.69e-12f,
        /*load_b_cost=*/8.12e-12f,
        /*output_c=*/1.62e-11f,
    },
#endif  // YNN_ARCH_X86_AMXFP16
#ifdef YNN_ARCH_X86_AMXINT8
    // Ratio (predicted / actual): std=0.067, min=0.878, max=1.083 (n=22)
    .x86_amx_int8 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.87e-12f,
        /*load_b_cost=*/4.11e-12f,
        /*output_c=*/2.04e-11f,
    },
    // Ratio (predicted / actual): std=0.067, min=0.878, max=1.083 (n=22)
    .x86_amx_uint8 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.87e-12f,
        /*load_b_cost=*/4.11e-12f,
        /*output_c=*/2.04e-11f,
    },
#endif  // YNN_ARCH_X86_AMXINT8
#ifdef YNN_ARCH_X86_AVX512VNNI
    // Ratio (predicted / actual): std=0.022, min=0.912, max=1.043 (n=59)
    .x86_avx512vnni_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.83e-10f,
        /*load_b_cost=*/2.35e-12f,
        /*output_c=*/7.95e-12f,
    },
    // Ratio (predicted / actual): std=0.069, min=0.814, max=1.114 (n=140)
    .x86_avx512vnni_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.08e-11f,
        /*load_b_cost=*/9.72e-12f,
        /*output_c=*/4.05e-11f,
    },
    // Ratio (predicted / actual): std=0.108, min=0.597, max=1.234 (n=238)
    .x86_avx512vnni_uint8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/4.85e-11f,
        /*load_b_cost=*/4.73e-12f,
        /*output_c=*/1.94e-11f,
    },
    // Ratio (predicted / actual): std=0.077, min=0.828, max=1.114 (n=80)
    .x86_avx512vnni_uint8_int8_int32_k16 = {
        /*block_overhead=*/9.01e-10f,
        /*load_a_cost=*/8.89e-12f,
        /*load_b_cost=*/7.51e-12f,
        /*output_c=*/1.07e-10f,
    },
#endif  // YNN_ARCH_X86_AVX512VNNI
#ifdef YNN_ARCH_X86_AVXVNNI
    // Ratio (predicted / actual): std=0.069, min=0.834, max=1.160 (n=60)
    .x86_avxvnni_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.29e-11f,
        /*load_b_cost=*/1.04e-11f,
        /*output_c=*/3.92e-11f,
    },
    // Ratio (predicted / actual): std=0.091, min=0.810, max=1.103 (n=80)
    .x86_avxvnni_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.71e-11f,
        /*load_b_cost=*/1.33e-11f,
        /*output_c=*/8.03e-11f,
    },
    // Ratio (predicted / actual): std=0.104, min=0.787, max=1.255 (n=120)
    .x86_avxvnni_uint8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.94e-11f,
        /*load_b_cost=*/7.02e-12f,
        /*output_c=*/3.66e-11f,
    },
#endif  // YNN_ARCH_X86_AVXVNNI
#ifdef YNN_ARCH_X86_AVX512BF16
    // Ratio (predicted / actual): std=0.192, min=0.657, max=1.396 (n=258)
    .x86_avx512bf16_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.27e-10f,
        /*load_b_cost=*/2.51e-11f,
        /*output_c=*/2.28e-11f,
    },
#endif  // YNN_ARCH_X86_AVX512BF16
#ifdef YNN_ARCH_X86_AVX512
    // Ratio (predicted / actual): std=0.124, min=0.695, max=1.241 (n=258)
    .x86_avx512_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.24e-10f,
        /*load_b_cost=*/1.90e-11f,
        /*output_c=*/2.01e-11f,
    },
    // Ratio (predicted / actual): std=0.096, min=0.678, max=1.193 (n=260)
    .x86_avx512_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.25e-10f,
        /*load_b_cost=*/2.94e-11f,
        /*output_c=*/1.69e-11f,
    },
    // Ratio (predicted / actual): std=0.098, min=0.737, max=1.206 (n=180)
    .x86_avx512_fp16_fp16_fp32 = {
        /*block_overhead=*/1.89e-10f,
        /*load_a_cost=*/4.14e-10f,
        /*load_b_cost=*/2.99e-11f,
        /*output_c=*/1.36e-11f,
    },
    // Ratio (predicted / actual): std=0.110, min=0.740, max=1.238 (n=178)
    .x86_avx512_fp32 = {
        /*block_overhead=*/7.04e-11f,
        /*load_a_cost=*/1.72e-10f,
        /*load_b_cost=*/1.89e-11f,
        /*output_c=*/2.02e-11f,
    },
    // Ratio (predicted / actual): std=0.108, min=0.736, max=1.204 (n=140)
    .x86_avx512_fp32_k2 = {
        /*block_overhead=*/3.86e-10f,
        /*load_a_cost=*/7.66e-11f,
        /*load_b_cost=*/2.03e-11f,
        /*output_c=*/5.39e-11f,
    },
    // Ratio (predicted / actual): std=0.108, min=0.758, max=1.234 (n=179)
    .x86_avx512_fp32_k4 = {
        /*block_overhead=*/9.19e-10f,
        /*load_a_cost=*/4.19e-11f,
        /*load_b_cost=*/1.94e-11f,
        /*output_c=*/1.27e-10f,
    },
    // Ratio (predicted / actual): std=0.105, min=0.749, max=1.233 (n=178)
    .x86_avx512_fp64 = {
        /*block_overhead=*/1.38e-10f,
        /*load_a_cost=*/1.71e-10f,
        /*load_b_cost=*/3.85e-11f,
        /*output_c=*/3.97e-11f,
    },
    // Ratio (predicted / actual): std=0.026, min=0.966, max=1.047 (n=20)
    .x86_avx512_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/0.00e+00f,
        /*load_b_cost=*/1.05e-11f,
        /*output_c=*/1.13e-11f,
    },
    // Ratio (predicted / actual): std=0.102, min=0.821, max=1.160 (n=140)
    .x86_avx512_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.62e-10f,
        /*load_b_cost=*/1.84e-11f,
        /*output_c=*/3.74e-11f,
    },
    // Ratio (predicted / actual): std=0.115, min=0.599, max=1.243 (n=140)
    .x86_avx512_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.40e-10f,
        /*load_b_cost=*/3.60e-11f,
        /*output_c=*/1.95e-11f,
    },
    // Ratio (predicted / actual): std=0.120, min=0.745, max=1.167 (n=140)
    .x86_avx512_int8_int8_int32_k16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.66e-11f,
        /*load_b_cost=*/1.67e-11f,
        /*output_c=*/2.86e-10f,
    },
    // Ratio (predicted / actual): std=0.016, min=0.959, max=1.039 (n=56)
    .x86_avx512_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.42e-10f,
        /*load_b_cost=*/3.09e-12f,
        /*output_c=*/1.92e-11f,
    },
    // Ratio (predicted / actual): std=0.114, min=0.778, max=1.223 (n=116)
    .x86_avx512_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.28e-11f,
        /*load_b_cost=*/1.46e-11f,
        /*output_c=*/7.35e-11f,
    },
#endif  // YNN_ARCH_X86_AVX512
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.110, min=0.770, max=1.211 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/2.48e-10f,
        /*load_a_cost=*/1.44e-10f,
        /*load_b_cost=*/2.74e-11f,
        /*output_c=*/3.70e-11f,
    },
    // Ratio (predicted / actual): std=0.104, min=0.768, max=1.202 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/1.65e-10f,
        /*load_a_cost=*/1.44e-10f,
        /*load_b_cost=*/5.44e-11f,
        /*output_c=*/7.55e-11f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.135, min=0.732, max=1.372 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.08e-10f,
        /*load_b_cost=*/3.73e-11f,
        /*output_c=*/4.41e-11f,
    },
    // Ratio (predicted / actual): std=0.076, min=0.841, max=1.170 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/3.01e-10f,
        /*load_a_cost=*/1.73e-10f,
        /*load_b_cost=*/4.24e-11f,
        /*output_c=*/3.73e-11f,
    },
    // Ratio (predicted / actual): std=0.035, min=0.943, max=1.085 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/9.86e-10f,
        /*load_a_cost=*/1.50e-11f,
        /*load_b_cost=*/4.62e-11f,
        /*output_c=*/4.72e-10f,
    },
    // Ratio (predicted / actual): std=0.096, min=0.830, max=1.228 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/1.79e-09f,
        /*load_a_cost=*/7.19e-11f,
        /*load_b_cost=*/2.55e-11f,
        /*output_c=*/5.12e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.095, min=0.878, max=1.217 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/7.65e-11f,
        /*load_a_cost=*/1.42e-10f,
        /*load_b_cost=*/1.23e-11f,
        /*output_c=*/3.50e-11f,
    },
    // Ratio (predicted / actual): std=0.028, min=0.938, max=1.056 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.87e-11f,
        /*load_b_cost=*/1.84e-11f,
        /*output_c=*/8.58e-11f,
    },
    // Ratio (predicted / actual): std=0.076, min=0.790, max=1.210 (n=100)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/3.21e-10f,
        /*load_a_cost=*/1.39e-10f,
        /*load_b_cost=*/4.19e-11f,
        /*output_c=*/4.40e-11f,
    },
    // Ratio (predicted / actual): std=0.013, min=0.979, max=1.026 (n=60)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/4.95e-10f,
        /*load_a_cost=*/2.89e-10f,
        /*load_b_cost=*/2.47e-12f,
        /*output_c=*/4.06e-11f,
    },
    // Ratio (predicted / actual): std=0.096, min=0.847, max=1.112 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.38e-11f,
        /*load_b_cost=*/1.98e-11f,
        /*output_c=*/1.18e-10f,
    },
    // Ratio (predicted / actual): std=0.116, min=0.767, max=1.268 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/1.32e-09f,
        /*load_a_cost=*/8.11e-11f,
        /*load_b_cost=*/3.74e-11f,
        /*output_c=*/7.73e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.082, min=0.817, max=1.163 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/1.23e-09f,
        /*load_a_cost=*/1.57e-10f,
        /*load_b_cost=*/3.49e-11f,
        /*output_c=*/2.65e-11f,
    },
    // Ratio (predicted / actual): std=0.084, min=0.812, max=1.164 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/1.17e-09f,
        /*load_a_cost=*/1.58e-10f,
        /*load_b_cost=*/6.93e-11f,
        /*output_c=*/5.43e-11f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.040, min=0.908, max=1.122 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/9.73e-10f,
        /*load_a_cost=*/4.67e-10f,
        /*load_b_cost=*/2.12e-11f,
        /*output_c=*/1.67e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.051, min=0.906, max=1.157 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/8.04e-10f,
        /*load_a_cost=*/5.50e-10f,
        /*load_b_cost=*/3.76e-11f,
        /*output_c=*/1.64e-11f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.108, min=0.792, max=1.221 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/1.07e-09f,
        /*load_a_cost=*/2.13e-10f,
        /*load_b_cost=*/6.95e-11f,
        /*output_c=*/4.81e-11f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_REDWOOD_COVE_H_
