// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_SAWTOOTH_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_SAWTOOTH_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models sawtooth = {
#ifndef YNN_DISABLE_SME
#ifdef YNN_ARCH_ARM64_SME2
    // Ratio (predicted / actual): std=0.118, min=0.836, max=1.265 (n=14)
    .arm64_sme2_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.45e-10f,
        /*load_b_cost=*/1.45e-10f,
        /*output_c=*/5.01e-11f,
    },
    // Ratio (predicted / actual): std=0.127, min=0.813, max=1.272 (n=14)
    .arm64_sme2_bf16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.37e-10f,
        /*load_b_cost=*/1.37e-10f,
        /*output_c=*/7.35e-11f,
    },
    // Ratio (predicted / actual): std=0.072, min=0.908, max=1.159 (n=14)
    .arm64_sme2_fp16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.63e-10f,
        /*load_b_cost=*/1.63e-10f,
        /*output_c=*/8.74e-11f,
    },
    // Ratio (predicted / actual): std=0.109, min=0.858, max=1.233 (n=14)
    .arm64_sme2_int8 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.04e-11f,
        /*load_b_cost=*/8.04e-11f,
        /*output_c=*/1.00e-10f,
    },
#endif  // YNN_ARCH_ARM64_SME2
#ifdef YNN_ARCH_ARM64_SME
    // Ratio (predicted / actual): std=0.060, min=0.945, max=1.183 (n=14)
    .arm64_sme_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.60e-10f,
        /*load_b_cost=*/1.60e-10f,
        /*output_c=*/8.03e-11f,
    },
    // Ratio (predicted / actual): std=0.064, min=0.933, max=1.178 (n=14)
    .arm64_sme_bf16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.69e-10f,
        /*load_b_cost=*/1.69e-10f,
        /*output_c=*/8.38e-11f,
    },
    // Ratio (predicted / actual): std=0.067, min=0.930, max=1.138 (n=14)
    .arm64_sme_fp16 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.66e-10f,
        /*load_b_cost=*/1.66e-10f,
        /*output_c=*/8.48e-11f,
    },
    // Ratio (predicted / actual): std=0.076, min=0.920, max=1.176 (n=14)
    .arm64_sme_int8 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.28e-11f,
        /*load_b_cost=*/8.28e-11f,
        /*output_c=*/8.87e-11f,
    },
    // Ratio (predicted / actual): std=0.155, min=0.790, max=1.291 (n=14)
    .arm64_sme_int4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.87e-11f,
        /*load_b_cost=*/6.87e-11f,
        /*output_c=*/9.20e-11f,
    },
    // Ratio (predicted / actual): std=0.073, min=0.903, max=1.139 (n=14)
    .arm64_sme_int2 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.17e-11f,
        /*load_b_cost=*/8.17e-11f,
        /*output_c=*/9.59e-11f,
    },
#endif  // YNN_ARCH_ARM64_SME
#endif  // YNN_DISABLE_SME
#ifdef YNN_ARCH_ARM64_NEONI8MM
    // Ratio (predicted / actual): std=0.194, min=0.722, max=1.722 (n=140)
    .arm64_neoni8mm_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.25e-10f,
        /*load_b_cost=*/9.18e-11f,
        /*output_c=*/3.81e-10f,
    },
    // Ratio (predicted / actual): std=0.185, min=0.691, max=1.658 (n=140)
    .arm64_neoni8mm_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.32e-10f,
        /*load_b_cost=*/1.00e-10f,
        /*output_c=*/3.48e-10f,
    },
    // Ratio (predicted / actual): std=0.212, min=0.651, max=1.641 (n=140)
    .arm64_neoni8mm_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.44e-10f,
        /*load_b_cost=*/6.04e-11f,
        /*output_c=*/3.25e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEONI8MM
#ifdef YNN_ARCH_ARM_NEONBF16
    // Ratio (predicted / actual): std=0.226, min=0.630, max=1.731 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k4 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/8.09e-10f,
        /*load_b_cost=*/3.38e-10f,
        /*output_c=*/3.92e-10f,
    },
    // Ratio (predicted / actual): std=0.195, min=0.655, max=1.746 (n=140)
    .arm_neonbf16_bf16_bf16_fp32_k2 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/7.12e-10f,
        /*load_b_cost=*/2.60e-10f,
        /*output_c=*/2.55e-10f,
    },
#endif  // YNN_ARCH_ARM_NEONBF16
#ifdef YNN_ARCH_ARM64_NEON
    // Ratio (predicted / actual): std=0.184, min=0.640, max=1.434 (n=198)
    .arm64_neon_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.32e-10f,
        /*load_b_cost=*/2.32e-10f,
        /*output_c=*/3.57e-10f,
    },
    // Ratio (predicted / actual): std=0.186, min=0.679, max=1.429 (n=200)
    .arm64_neon_fp64 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.47e-10f,
        /*load_b_cost=*/4.51e-10f,
        /*output_c=*/7.03e-10f,
    },
    // Ratio (predicted / actual): std=0.176, min=0.693, max=1.595 (n=200)
    .arm64_neon_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/5.72e-10f,
        /*load_b_cost=*/2.67e-10f,
        /*output_c=*/4.63e-10f,
    },
#endif  // YNN_ARCH_ARM64_NEON
#ifdef YNN_ARCH_ARM_NEONDOT
    // Ratio (predicted / actual): std=0.135, min=0.737, max=1.395 (n=120)
    .arm_neondot_int8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.37e-10f,
        /*load_b_cost=*/6.23e-11f,
        /*output_c=*/3.31e-10f,
    },
    // Ratio (predicted / actual): std=0.193, min=0.716, max=1.482 (n=160)
    .arm_neondot_int8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.63e-10f,
        /*load_b_cost=*/7.86e-11f,
        /*output_c=*/2.84e-10f,
    },
    // Ratio (predicted / actual): std=0.218, min=0.688, max=1.613 (n=180)
    .arm_neondot_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.38e-10f,
        /*load_b_cost=*/5.63e-11f,
        /*output_c=*/4.18e-10f,
    },
#endif  // YNN_ARCH_ARM_NEONDOT
#ifdef YNN_ARCH_ARM_NEON
    // Ratio (predicted / actual): std=0.189, min=0.576, max=2.526 (n=200)
    .arm_neon_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.13e-10f,
        /*load_b_cost=*/2.53e-10f,
        /*output_c=*/7.16e-10f,
    },
#endif  // YNN_ARCH_ARM_NEON
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_SAWTOOTH_H_
