// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ZEN2_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ZEN2_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models zen2 = {
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.131, min=0.703, max=1.293 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/3.00e-10f,
        /*load_a_cost=*/2.00e-10f,
        /*load_b_cost=*/4.34e-11f,
        /*output_c=*/6.91e-11f,
    },
    // Ratio (predicted / actual): std=0.129, min=0.706, max=1.287 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/1.82e-10f,
        /*load_a_cost=*/1.99e-10f,
        /*load_b_cost=*/8.69e-11f,
        /*output_c=*/1.41e-10f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.148, min=0.705, max=1.282 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.17e-10f,
        /*load_b_cost=*/6.61e-11f,
        /*output_c=*/7.38e-11f,
    },
    // Ratio (predicted / actual): std=0.073, min=0.853, max=1.205 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.08e-10f,
        /*load_b_cost=*/5.59e-11f,
        /*output_c=*/7.58e-11f,
    },
    // Ratio (predicted / actual): std=0.037, min=0.933, max=1.134 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/5.96e-10f,
        /*load_a_cost=*/5.55e-12f,
        /*load_b_cost=*/1.65e-10f,
        /*output_c=*/9.72e-10f,
    },
    // Ratio (predicted / actual): std=0.117, min=0.771, max=1.262 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/5.13e-09f,
        /*load_a_cost=*/1.15e-10f,
        /*load_b_cost=*/3.80e-11f,
        /*output_c=*/9.47e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.103, min=0.861, max=1.225 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.16e-10f,
        /*load_b_cost=*/2.23e-11f,
        /*output_c=*/6.83e-11f,
    },
    // Ratio (predicted / actual): std=0.021, min=0.935, max=1.062 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.37e-10f,
        /*load_b_cost=*/2.36e-11f,
        /*output_c=*/2.25e-10f,
    },
    // Ratio (predicted / actual): std=0.025, min=0.926, max=1.069 (n=60)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.85e-10f,
        /*load_b_cost=*/3.84e-11f,
        /*output_c=*/8.96e-11f,
    },
    // Ratio (predicted / actual): std=0.200, min=0.644, max=1.396 (n=120)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.23e-10f,
        /*load_b_cost=*/2.26e-11f,
        /*output_c=*/2.23e-10f,
    },
    // Ratio (predicted / actual): std=0.091, min=0.856, max=1.127 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/6.77e-11f,
        /*load_b_cost=*/2.92e-11f,
        /*output_c=*/2.10e-10f,
    },
    // Ratio (predicted / actual): std=0.100, min=0.792, max=1.258 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/3.36e-09f,
        /*load_a_cost=*/1.29e-10f,
        /*load_b_cost=*/5.07e-11f,
        /*output_c=*/1.77e-10f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.075, min=0.790, max=1.166 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/2.05e-09f,
        /*load_a_cost=*/2.53e-10f,
        /*load_b_cost=*/4.63e-11f,
        /*output_c=*/5.28e-11f,
    },
    // Ratio (predicted / actual): std=0.072, min=0.807, max=1.155 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/2.14e-09f,
        /*load_a_cost=*/2.54e-10f,
        /*load_b_cost=*/9.28e-11f,
        /*output_c=*/1.00e-10f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.092, min=0.849, max=1.199 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/1.59e-09f,
        /*load_a_cost=*/6.03e-10f,
        /*load_b_cost=*/4.41e-11f,
        /*output_c=*/4.10e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.046, min=0.917, max=1.143 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/1.69e-09f,
        /*load_a_cost=*/8.28e-10f,
        /*load_b_cost=*/5.11e-11f,
        /*output_c=*/3.26e-11f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.116, min=0.727, max=1.205 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/1.35e-09f,
        /*load_a_cost=*/3.18e-10f,
        /*load_b_cost=*/1.27e-10f,
        /*output_c=*/1.29e-10f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ZEN2_H_
