// Copyright 2026 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

// Generated by fit_cost_models.py.

// clang-format off

#ifndef XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ZEN3_H_
#define XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ZEN3_H_

#include "ynnpack/kernels/dot/cost_model/cost_model.h"

namespace ynn {

static constexpr dot_cost_models zen3 = {
#ifdef YNN_ARCH_X86_FMA3
    // Ratio (predicted / actual): std=0.134, min=0.735, max=1.341 (n=140)
    .x86_fma3_fp32 = {
        /*block_overhead=*/6.71e-10f,
        /*load_a_cost=*/1.69e-10f,
        /*load_b_cost=*/2.94e-11f,
        /*output_c=*/4.80e-11f,
    },
    // Ratio (predicted / actual): std=0.131, min=0.729, max=1.319 (n=140)
    .x86_fma3_fp64 = {
        /*block_overhead=*/1.84e-10f,
        /*load_a_cost=*/1.71e-10f,
        /*load_b_cost=*/5.70e-11f,
        /*output_c=*/1.09e-10f,
    },
#endif  // YNN_ARCH_X86_FMA3
#ifdef YNN_ARCH_X86_AVX2_FMA3
    // Ratio (predicted / actual): std=0.204, min=0.695, max=1.369 (n=160)
    .x86_avx2_fma3_bf16_bf16_fp32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.56e-10f,
        /*load_b_cost=*/4.68e-11f,
        /*output_c=*/6.00e-11f,
    },
    // Ratio (predicted / actual): std=0.075, min=0.851, max=1.234 (n=140)
    .x86_avx2_fma3_bf16_bf16_fp32_k1 = {
        /*block_overhead=*/2.13e-10f,
        /*load_a_cost=*/1.83e-10f,
        /*load_b_cost=*/4.96e-11f,
        /*output_c=*/5.48e-11f,
    },
    // Ratio (predicted / actual): std=0.059, min=0.873, max=1.176 (n=40)
    .x86_avx2_fma3_fp32_k8 = {
        /*block_overhead=*/1.27e-09f,
        /*load_a_cost=*/1.31e-11f,
        /*load_b_cost=*/7.00e-11f,
        /*output_c=*/5.33e-10f,
    },
    // Ratio (predicted / actual): std=0.105, min=0.779, max=1.213 (n=180)
    .x86_avx2_fma3_fp32_k2 = {
        /*block_overhead=*/3.24e-09f,
        /*load_a_cost=*/8.58e-11f,
        /*load_b_cost=*/2.87e-11f,
        /*output_c=*/8.70e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2_FMA3
#ifdef YNN_ARCH_X86_AVX2
    // Ratio (predicted / actual): std=0.090, min=0.879, max=1.200 (n=80)
    .x86_avx2_int8_int8_int32_symmetric_b = {
        /*block_overhead=*/3.82e-10f,
        /*load_a_cost=*/1.45e-10f,
        /*load_b_cost=*/1.30e-11f,
        /*output_c=*/5.01e-11f,
    },
    // Ratio (predicted / actual): std=0.040, min=0.937, max=1.066 (n=60)
    .x86_avx2_int8_int8_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/1.19e-10f,
        /*load_b_cost=*/1.45e-11f,
        /*output_c=*/1.53e-10f,
    },
    // Ratio (predicted / actual): std=0.072, min=0.817, max=1.219 (n=100)
    .x86_avx2_int8_int8_int32_k1 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.06e-10f,
        /*load_b_cost=*/3.16e-11f,
        /*output_c=*/7.16e-11f,
    },
    // Ratio (predicted / actual): std=0.013, min=0.957, max=1.033 (n=60)
    .x86_avx2_uint8_int2_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/2.65e-10f,
        /*load_b_cost=*/2.73e-12f,
        /*output_c=*/7.24e-11f,
    },
    // Ratio (predicted / actual): std=0.065, min=0.889, max=1.069 (n=60)
    .x86_avx2_uint8_int4_int32 = {
        /*block_overhead=*/0.00e+00f,
        /*load_a_cost=*/3.90e-11f,
        /*load_b_cost=*/1.91e-11f,
        /*output_c=*/1.37e-10f,
    },
    // Ratio (predicted / actual): std=0.095, min=0.795, max=1.275 (n=180)
    .x86_avx2_fp32_k2 = {
        /*block_overhead=*/3.24e-09f,
        /*load_a_cost=*/8.58e-11f,
        /*load_b_cost=*/4.08e-11f,
        /*output_c=*/9.95e-11f,
    },
#endif  // YNN_ARCH_X86_AVX2
#ifdef YNN_ARCH_X86_AVX
    // Ratio (predicted / actual): std=0.100, min=0.793, max=1.170 (n=140)
    .x86_avx_fp32 = {
        /*block_overhead=*/1.75e-09f,
        /*load_a_cost=*/1.77e-10f,
        /*load_b_cost=*/4.01e-11f,
        /*output_c=*/3.58e-11f,
    },
    // Ratio (predicted / actual): std=0.098, min=0.795, max=1.165 (n=140)
    .x86_avx_fp64 = {
        /*block_overhead=*/1.96e-09f,
        /*load_a_cost=*/1.71e-10f,
        /*load_b_cost=*/7.72e-11f,
        /*output_c=*/6.57e-11f,
    },
#endif  // YNN_ARCH_X86_AVX
#ifdef YNN_ARCH_X86_F16C_FMA3
    // Ratio (predicted / actual): std=0.038, min=0.871, max=1.160 (n=100)
    .x86_f16c_fma3_fp16_fp16_fp32 = {
        /*block_overhead=*/1.57e-09f,
        /*load_a_cost=*/5.85e-10f,
        /*load_b_cost=*/2.06e-11f,
        /*output_c=*/2.08e-11f,
    },
#endif  // YNN_ARCH_X86_F16C_FMA3
#ifdef YNN_ARCH_X86_F16C
    // Ratio (predicted / actual): std=0.059, min=0.888, max=1.117 (n=140)
    .x86_f16c_fp16_fp16_fp32 = {
        /*block_overhead=*/1.77e-09f,
        /*load_a_cost=*/5.85e-10f,
        /*load_b_cost=*/4.59e-11f,
        /*output_c=*/1.97e-11f,
    },
#endif  // YNN_ARCH_X86_F16C
#ifdef YNN_ARCH_X86_SSE2
    // Ratio (predicted / actual): std=0.150, min=0.630, max=1.231 (n=160)
    .x86_sse2_fp32 = {
        /*block_overhead=*/1.26e-09f,
        /*load_a_cost=*/2.42e-10f,
        /*load_b_cost=*/8.88e-11f,
        /*output_c=*/9.31e-11f,
    },
#endif  // YNN_ARCH_X86_SSE2
};

}  // namespace ynn

#endif  // XNNPACK_YNNPACK_KERNELS_DOT_COST_MODEL_ZEN3_H_
