# Copyright 2026 Google LLC
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Mapping from architecture name to the enablement variable.
FUNCTION(YNN_CHECK_ARCH_ENABLED ARCH VAR)
  IF(ARCH STREQUAL "x86_sse2")
    SET(${VAR} ${YNN_ENABLE_X86_SSE2} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_ssse3")
    SET(${VAR} ${YNN_ENABLE_X86_SSSE3} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_sse41")
    SET(${VAR} ${YNN_ENABLE_X86_SSE41} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_avx")
    SET(${VAR} ${YNN_ENABLE_X86_AVX} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_f16c")
    SET(${VAR} ${YNN_ENABLE_X86_F16C} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_f16c_fma3")
    SET(${VAR} ${YNN_ENABLE_X86_F16C_FMA3} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_avx2")
    SET(${VAR} ${YNN_ENABLE_X86_AVX2} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_fma3")
    SET(${VAR} ${YNN_ENABLE_X86_FMA3} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_avx2_fma3")
    SET(${VAR} ${YNN_ENABLE_X86_AVX2_FMA3} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_avx512")
    SET(${VAR} ${YNN_ENABLE_X86_AVX512} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_avx512bf16")
    SET(${VAR} ${YNN_ENABLE_X86_AVX512BF16} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_avx512fp16")
    SET(${VAR} ${YNN_ENABLE_X86_AVX512FP16} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_avx512vnni")
    SET(${VAR} ${YNN_ENABLE_X86_AVX512VNNI} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_amxbf16")
    SET(${VAR} ${YNN_ENABLE_X86_AMXBF16} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_amxfp16")
    SET(${VAR} ${YNN_ENABLE_X86_AMXFP16} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "x86_amxint8")
    SET(${VAR} ${YNN_ENABLE_X86_AMXINT8} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm_neon")
    SET(${VAR} ${YNN_ENABLE_ARM_NEON} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm_neondot")
    SET(${VAR} ${YNN_ENABLE_ARM_NEONDOT} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm_neonfma")
    SET(${VAR} ${YNN_ENABLE_ARM_NEONFMA} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm_neonfp16")
    SET(${VAR} ${YNN_ENABLE_ARM_NEONFP16} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm_neonfp16arith")
    SET(${VAR} ${YNN_ENABLE_ARM_NEONFP16ARITH} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm_neonbf16")
    SET(${VAR} ${YNN_ENABLE_ARM_NEONBF16} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm64_neon")
    SET(${VAR} ${YNN_ENABLE_ARM64_NEON} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm64_neoni8mm")
    SET(${VAR} ${YNN_ENABLE_ARM64_NEONI8MM} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm64_sme")
    SET(${VAR} ${YNN_ENABLE_ARM64_SME} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm64_sme2")
    SET(${VAR} ${YNN_ENABLE_ARM64_SME2} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "arm64_sve")
    SET(${VAR} ${YNN_ENABLE_ARM64_SVE} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "hexagon_hvx")
    SET(${VAR} ${YNN_ENABLE_HVX} PARENT_SCOPE)
  ELSEIF(ARCH STREQUAL "wasm_simd128")
    SET(${VAR} ${YNN_ENABLE_WASM_SIMD128} PARENT_SCOPE)
  ELSE()
    SET(${VAR} OFF PARENT_SCOPE)
  ENDIF()
ENDFUNCTION()

# Function to get compiler flags for a specific architecture.
FUNCTION(YNN_GET_ARCH_COPTS ARCH VAR)
  IF(MSVC)
    IF(ARCH MATCHES "^x86_avx512")
      SET(${VAR} "/arch:AVX512" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx2" OR ARCH STREQUAL "x86_avx2_fma3")
      SET(${VAR} "/arch:AVX2" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx" OR ARCH STREQUAL "x86_fma3" OR ARCH STREQUAL "x86_f16c")
      SET(${VAR} "/arch:AVX" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_sse2" OR ARCH STREQUAL "x86_ssse3" OR ARCH STREQUAL "x86_sse41")
      SET(${VAR} "/arch:SSE2" PARENT_SCOPE)
    ELSE()
      SET(${VAR} "" PARENT_SCOPE)
    ENDIF()
  ELSE()
    IF(ARCH STREQUAL "x86_sse2")
      SET(${VAR} "-msse2" "-mno-ssse3" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_ssse3")
      SET(${VAR} "-mssse3" "-mno-sse4.1" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_sse41")
      SET(${VAR} "-msse4.1" "-mno-sse4.2" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx")
      SET(${VAR} "-mavx" "-mno-avx2" "-mno-f16c" "-mno-fma" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_f16c")
      SET(${VAR} "-mf16c" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_f16c_fma3")
      SET(${VAR} "-mf16c" "-mavx" "-mfma" "-mno-avx2" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx2")
      SET(${VAR} "-mavx2" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_fma3")
      SET(${VAR} "-mavx" "-mfma" "-mno-avx2" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx2_fma3")
      SET(${VAR} "-mavx2" "-mfma" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx512")
      SET(${VAR} "-mavx512f" "-mavx512bw" "-mavx512vl" "-mavx512dq" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx512bf16")
      SET(${VAR} "-mavx512f" "-mavx512bw" "-mavx512vl" "-mavx512dq" "-mavx512bf16" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx512fp16")
      SET(${VAR} "-mavx512f" "-mavx512bw" "-mavx512vl" "-mavx512dq" "-mavx512fp16" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_avx512vnni")
      SET(${VAR} "-mavx512f" "-mavx512bw" "-mavx512vl" "-mavx512dq" "-mavx512vnni" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_amxbf16")
      SET(${VAR} "-mamx-tile" "-mamx-bf16" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_amxfp16")
      SET(${VAR} "-mamx-tile" "-mamx-fp16" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "x86_amxint8")
      SET(${VAR} "-mamx-tile" "-mamx-int8" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "arm_neon")
      IF(YNNPACK_TARGET_PROCESSOR STREQUAL "arm")
        SET(${VAR} "-marm" "-march=armv7-a" "-mfpu=neon" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm_neondot")
      IF(YNNPACK_TARGET_PROCESSOR STREQUAL "arm")
        SET(${VAR} "-marm" "-march=armv8.2-a+dotprod" "-mfpu=neon-fp-armv8" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "-march=armv8.2-a+dotprod" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm_neonfma")
      IF(YNNPACK_TARGET_PROCESSOR STREQUAL "arm")
        SET(${VAR} "-marm" "-march=armv7-a" "-mfpu=neon-vfpv4" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm_neonfp16")
      IF(YNNPACK_TARGET_PROCESSOR STREQUAL "arm")
        SET(${VAR} "-marm" "-march=armv7-a" "-mfpu=neon-fp16" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm_neonfp16arith")
      IF(YNNPACK_TARGET_PROCESSOR STREQUAL "arm")
        SET(${VAR} "-marm" "-march=armv8.2-a+fp16" "-mfpu=neon-fp-armv8" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "-march=armv8.2-a+fp16" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm_neonbf16")
      IF(YNNPACK_TARGET_PROCESSOR STREQUAL "arm")
        SET(${VAR} "-marm" "-march=armv8.2-a+bf16" "-mfpu=neon-fp-armv8" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "-march=armv8.2-a+bf16" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm64_neon")
      SET(${VAR} "" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "arm64_neoni8mm")
      SET(${VAR} "-march=armv8.2-a+i8mm" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "arm64_sme")
      IF(APPLE)
        SET(${VAR} "-march=armv8.2-a+sme" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "-march=armv8.2-a+sve+sme" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm64_sme2")
      IF(APPLE)
        SET(${VAR} "-march=armv8.2-a+sme2" PARENT_SCOPE)
      ELSE()
        SET(${VAR} "-march=armv8.2-a+sve+sme2" PARENT_SCOPE)
      ENDIF()
    ELSEIF(ARCH STREQUAL "arm64_sve")
      SET(${VAR} "-march=armv8.2-a+sve" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "hexagon_hvx")
      SET(${VAR} "-mhvx" PARENT_SCOPE)
    ELSEIF(ARCH STREQUAL "wasm_simd128")
      SET(${VAR} "-msimd128" PARENT_SCOPE)
    ELSE()
      SET(${VAR} "" PARENT_SCOPE)
    ENDIF()
  ENDIF()
ENDFUNCTION()
