mkdir build\windows
mkdir build\windows\arm64ec

set CMAKE_ARGS=-DXNNPACK_LIBRARY_TYPE=static -DXNNPACK_ENABLE_ASSEMBLY=OFF -DXNNPACK_ENABLE_ARM_FP16_SCALAR=OFF -DXNNPACK_ENABLE_ARM_BF16=OFF
set CMAKE_ARGS=%CMAKE_ARGS% -DXNNPACK_PLATFORM_JIT=OFF -DXNNPACK_ENABLE_JIT=OFF
set CMAKE_ARGS=%CMAKE_ARGS% -G="Visual Studio 17 2022" -A ARM64 -DCMAKE_C_FLAGS=/arm64EC -DCMAKE_CXX_FLAGS=/arm64EC -DCMAKE_EXE_LINKER_FLAGS=/MACHINE:ARM64EC -DCMAKE_SHARED_LINKER_FLAGS=/MACHINE:ARM64EC -DCMAKE_MODULE_LINKER_FLAGS=/MACHINE:ARM64EC

rem Use-specified CMake arguments go last to allow overridding defaults
set CMAKE_ARGS=%CMAKE_ARGS% %*

echo %CMAKE_ARGS%

cd build\windows\arm64ec && cmake ..\..\.. %CMAKE_ARGS%
cmake --build . -j %NUMBER_OF_PROCESSORS% --config Release
